version: '3.8'

services:
  substrate-node:
    image: parity/substrate:latest
    command: 
      - "--dev"
      - "--tmp"
      - "--rpc-cors=all"
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
    ports:
      - "9944:9944"
